language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli codeclimate-test-reporter
install:
  - npm install
after_script:
  - codeclimate < coverage/lcov.info
notifications:
  email:
    on_success: change
    on_failure: always
