language: node_js
node_js:
  - "4.2"
install:
  - npm install
after_script:
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
